from pydantic import BaseModel, Field
from typing import Annotated, Sequence
from langchain_core.messages import BaseMessage
from hackathon.models import Dish
from langgraph.graph.message import add_messages


class GraphState(BaseModel):
    """
    Represents the state of our graph.

    Attributes:
        question: The question asked by the user.
        question_id: The id of the user's question.
        dishes: A list of dishes that satisfy the user's question.
        messages: The messages generated by the CypherAgent.
    """

    question: str = Field(description="La domanda dell'utente.", default="")
    question_id: int = Field(description="L'id della domanda dell'utente.", default=0)
    dishes: list[Dish] = Field(
        description="Lista di piatti che soddisfano la domanda dell'utente",
        default_factory=list,
    )
    messages: Annotated[Sequence[BaseMessage], add_messages] = Field(
        description="I messaggi generati dal CypherAgent", default_factory=list
    )
