from pydantic import BaseModel, Field
from typing import Annotated, Sequence
from langchain_core.messages import BaseMessage
from hackathon.models import Dish, Planet
from langgraph.graph.message import add_messages


class GraphState(BaseModel):
    """
    Represents the state of our graph.

    Attributes:
        question: The question asked by the user.
        question_id: The id of the user's question.
        dishes: A list of dishes that satisfy the user's question.
        involves_planet: Whether the user's question involves a specific Planet.
        involved_planet: The Planet to which the user's query refers.
        cypher_agent_messages: The messages generated by the CypherAgent.
        cypher_query: The Cypher query generated to satisfy the user's question.
    """

    question: str = Field(description="La domanda dell'utente.", default="")
    question_id: int = Field(description="L'id della domanda dell'utente.", default=0)
    dishes: list[Dish] = Field(
        description="Lista di piatti che soddisfano la domanda dell'utente",
        default_factory=list,
    )
    involves_planet: bool = Field(
        description="La domanda dell'utente fa riferimento ad uno specifico Pianeta",
        default=False,
    )
    involved_planet: Planet | None = Field(
        description="Il pianeta al quale la query dell'utente fa riferimento",
        default=None,
    )
    messages: Annotated[Sequence[BaseMessage], add_messages] = Field(
        description="I messaggi generati dal CypherAgent", default_factory=list
    )

    cypher_query: str = Field(
        description="La query Cypher generata per soddisfare la domanda dell'utente",
        default="",
    )
